# Generated by Django 5.1.1 on 2024-10-10 17:55

import appointments.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('address', models.CharField(max_length=300, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Clinic',
                'verbose_name_plural': 'Clinics',
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(validators=[appointments.validators.validate_not_past_date], verbose_name='Start time')),
                ('end_time', models.DateTimeField(verbose_name='End time')),
                ('selectable_time_list', models.JSONField(blank=True, default=dict, null=True, verbose_name='Selectable times')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.doctor', verbose_name='Doctor')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.clinic', verbose_name='Clinic')),
            ],
            options={
                'verbose_name': 'Availability',
                'verbose_name_plural': 'Availabilities',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_time', models.CharField(blank=True, max_length=5, null=True, verbose_name='Selected Time')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient', verbose_name='Patient')),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.availability', verbose_name='Availability')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'unique_together': {('patient', 'availability')},
            },
        ),
    ]
